#!/usr/bin/python

#
# Copyright (C) 2019 Nethesis S.r.l.
# http://www.nethesis.it - nethserver@nethesis.it
#
# This script is part of NethServer.
#
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
#
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see COPYING.
#

import sys
import fileinput
import subprocess
import simplejson
import tempfile
import socket

def read_proxy_status():
    bash_command = "/sbin/e-smith/config getjson squid"
    process = subprocess.Popen(bash_command.split(), stdout=subprocess.PIPE)
    output, error = process.communicate()
    
    # getjson return 1 for unknown configurations
    if not output or output == "1":
        return "unknown"
    
    config_json = simplejson.loads(output)
    proxy_status = config_json['props']['status']
    return proxy_status

try:
    line = fileinput.input()[0].rstrip()
    input_json = simplejson.loads(line)
    proxy_status = read_proxy_status()
    output = simplejson.dumps({'proxyStatus': proxy_status})
    print (output)
except Exception, e:
    print simplejson.dumps({ 'error': "%s" % e })
    sys.exit(1)
