#!/usr/bin/perl -w
#
# Copyright (C) 2018 Nethesis S.r.l.
#
# This script is part of NethServer.
#
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
#
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see <http://www.gnu.org/licenses/>.
#

use esmith::Build::CreateLinks qw(:all);

#
# nethserver-dedalo-update event
#

my $event = 'nethserver-dedalo-update';

event_actions($event, qw(
    initialize-default-databases 00
    nethserver-dedalo-conf 20
));

event_templates($event,
   '/opt/icaro/dedalo/config'
);

event_services($event, qw(
    dedalo_users_auth restart
));

#
# nethserver-dedalo-save event
#

$event = 'nethserver-dedalo-save';

event_templates($event,
   '/opt/icaro/dedalo/config'
);

event_actions($event, qw(
    nethserver-dedalo-proxyconfig 20
    nethserver-dedalo-conf 25
    firewall-adjust 30
));

event_services($event, qw(
    dedalo restart
));

#
# nethserver-dedalo-register event
#

$event = 'nethserver-dedalo-register';

event_templates($event,
   '/opt/icaro/dedalo/config'
);

event_actions($event, qw(
    nethserver-dedalo-register 20
    firewall-adjust 30
));

event_services($event, qw(
    dedalo restart
));

#
# nethserver-dedalo-unregister event
#

$event = 'nethserver-dedalo-unregister';

event_actions($event, qw(
    nethserver-dedalo-unregister 20
    firewall-adjust 60
));

event_services($event, qw(
    dedalo stop
));

#
# post-restore-config event
#

$event = 'post-restore-config';

event_actions($event, qw(
    nethserver-dedalo-network-reset 03
));
