#!/usr/bin/python

#
# Copyright (C) 2019 Nethesis S.r.l.
# http://www.nethesis.it - nethserver@nethesis.it
#
# This script is part of NethServer.
#
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
#
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see COPYING.
#

import sys
import subprocess
import simplejson
import fileinput
import os
import tempfile
import shlex
import ipaddress

def register(input_json):
    hotspot_id = input_json['hotspotId']
    hotspot_name = input_json['hotspotName']
    unit_description = input_json['unitDescription']
    network_device = input_json['networkDevice']
    network_address = input_json['networkAddress']
    hostname = input_json['hostname']
    unit_name = input_json['unitName']
    dhcp_range_start = input_json['dhcpRangeStart']
    dhcp_range_end = input_json['dhcpRangeEnd']

    # convert dhcp range values to integer
    network_ip_string = network_address.split("/")[0]
    network_int = int(ipaddress.IPv4Address(u'' + network_ip_string))
    dhcp_range_start_int = int(ipaddress.IPv4Address(u'' + dhcp_range_start))
    dhcp_range_end_int = int(ipaddress.IPv4Address(u'' + dhcp_range_end))

    config_dhcp_start = dhcp_range_start_int - network_int
    config_dhcp_end = dhcp_range_end_int - network_int

    try:
        command_args = ['/sbin/e-smith/config', 'setprop', 'dedalo', 'Id', str(hotspot_id), 'Name', hotspot_name, 'Description', unit_description, 'IcaroHost', hostname, 'UnitName', unit_name, 'Network', network_address, 'DhcpStart', str(config_dhcp_start), 'DhcpEnd', str(config_dhcp_end)]
        process = subprocess.Popen(command_args, stdout=sys.stdout, stderr=sys.stderr)
        output, error = process.communicate()
    except Exception, e:
        return "Error setting props: %s" % e

    # release hotspot role for not selected devices
    try:
        bash_command = "/sbin/e-smith/db networks getjson"
        process = subprocess.Popen(bash_command.split(), stdout=subprocess.PIPE)
        output, error = process.communicate()
    except Exception, e:
        return "Error retrieving db networks: %s" % e

    networks_json = simplejson.loads(output)
    role_reset = False

    for network in networks_json:
        if 'role' in network['props'] and network['props']['role'] == 'hotspot':
            # reset only not selected devices
            if network['name'] != network_device:
                role_reset = True

                try:
                    command_args = ['/sbin/e-smith/db', 'networks', 'set', network['name'], network['type'], 'role', '']
                    process = subprocess.Popen(command_args, stdout=sys.stdout, stderr=sys.stderr)
                    output, error = process.communicate()
                except Exception, e:
                    return "Error releasing hotspot role for network %s: %s" % (network['name'], e)

    # set hotspot role and reset ip address for selected device
    try:
        command_args = [ '/sbin/e-smith/db', 'networks', 'setprop', network_device, 'role', 'hotspot', 'ipaddr', '', 'netmask', '' ]
        process = subprocess.Popen(command_args, stdout=sys.stdout, stderr=sys.stderr)
        output, error = process.communicate()
    except Exception, e:
        return "Error setting hotspot role for network %s: %s" % (network, e)

    # perform interface-update if selected device is not physical, or at least an interface role has been removed (role_reset = True)
    try:
        bash_command = "/sbin/e-smith/db networks gettype %s" % network_device
        process = subprocess.Popen(bash_command.split(), stdout=subprocess.PIPE)
        output, error = process.communicate()
        return_code = process.returncode

        if return_code != 0:
            return "Event failed, see /var/log/messages"

        if output.rstrip() != "ethernet" or role_reset:
            bash_command = "/sbin/e-smith/signal-event -j interface-update"
            process = subprocess.Popen(bash_command.split(), stdout=sys.stdout, stderr=sys.stderr)
            output, error = process.communicate()
            return_code = process.returncode

            if return_code != 0:
                return "Event failed, see /var/log/messages"
    except Exception, e:
        return "Event failed, see /var/log/messages: %s" % e

    token_json = None

    # write token to temp file
    with open(os.getenv("HOME") + '/.dedalo-token') as f:
        token_file = f.read()
        token_json = simplejson.loads(token_file)
    f.closed

    token = token_json['token']

    with tempfile.NamedTemporaryFile(delete=False) as tmp_file:
        tmp_file.write(token)
        tmp_file.flush()

        try:
            bash_command = "/sbin/e-smith/signal-event -j nethserver-dedalo-register %s" % tmp_file.name
            process = subprocess.Popen(bash_command.split(), stdout=sys.stdout, stderr=sys.stderr)
            output, error = process.communicate()
            return_code = process.returncode

            if return_code != 0:
                return "Event failed, see /var/log/messages"
        except Exception, e:
            return "Event failed, see /var/log/messages: %s" % e
            
def unregister(input_json, logout_user):
    try:
        bash_command = "/sbin/e-smith/signal-event -j nethserver-dedalo-unregister"
        process = subprocess.Popen(bash_command.split(), stdout=sys.stdout, stderr=sys.stderr)
        output, error = process.communicate()
        return_code = process.returncode

        if return_code != 0:
            return "Event failed, see /var/log/messages"

        if logout_user:
            os.remove(os.getenv("HOME") + '/.dedalo-token')
    except Exception, e:
        return "Event failed, see /var/log/messages: %s" % e

try:
    line = fileinput.input()[0].rstrip()
    input_json = simplejson.loads(line)
    app_info = input_json["action"]

    if app_info == 'register':
        error = register(input_json)
    elif app_info == 'unregister':
        logout = input_json["logout"]
        error = unregister(input_json, logout)
        
    if error:
        output = simplejson.dumps({'state': 'error', 'message': error})
        print(output)
        sys.exit(1)
    else:
        output = simplejson.dumps({'state': 'success'})
        print(output)
except Exception, e:
    print simplejson.dumps({ 'error': "%s" % e })
    sys.exit(1)
