#!/bin/bash

#
# Copyright (C) 2019 Nethesis S.r.l.
# http://www.nethesis.it - nethserver@nethesis.it
#
# This script is part of NethServer.
#
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
#
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see COPYING.
#

. /usr/libexec/nethserver/api/lib/helper_functions

function _get
{
    field=$1
    echo $data | jq -r ".$field"
}

# read input json
data=$(cat /dev/stdin)

hotspot_id=$(_get hotspotId)
hotspot_name=$(_get hotspotName)
unit_description=$(_get unitDescription)
network_device=$(_get networkDevice)
hostname=$(_get hostname)
unit_name=$(_get unitName)

# update dedalo configuration
/sbin/e-smith/config setprop dedalo Id "$hotspot_id" Name "$hotspot_name" Description "$unit_description" IcaroHost "$hostname" UnitName "$unit_name" status enabled

if [ $? -gt 0 ]; then
    invalid_error
fi

# todo uncomment!
# /sbin/e-smith/signal-event -j nethserver-dedalo-register
# if [ $? -gt 0 ]; then
#     error "EventFailed" "See /var/log/messages"
# else
#     success
# fi
