#!/usr/bin/python

#
# Copyright (C) 2019 Nethesis S.r.l.
# http://www.nethesis.it - nethserver@nethesis.it
#
# This script is part of NethServer.
#
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
#
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see COPYING.
#

import sys
import fileinput
import subprocess
import simplejson
import tempfile
import socket
import ipaddress

def read_network_devices():
    bash_command = "/sbin/e-smith/db networks getjson"
    process = subprocess.Popen(bash_command.split(), stdout=subprocess.PIPE)
    output, error = process.communicate()
    db_networks = simplejson.loads(output)
    device_types = [ "ethernet", "bridge", "bond", "vlan" ]
    network_devices = []

    for elem in db_networks:
        if elem["type"] in device_types:
            # return only devices with role "hotspot" or empty
            if "role" in elem["props"] and (elem["props"]["role"] == "hotspot" or (not elem["props"]["role"])):
                name = elem["name"]
                ip_address = ""

                if elem["props"]["role"] == "hotspot":
                    hotspot_assigned = True
                else:
                    hotspot_assigned = False

                if "ipaddr" in elem["props"]:
                    ip_address = elem["props"]["ipaddr"]
                
                network_device = { "name": name, "hotspot_assigned": hotspot_assigned, "ip_address": ip_address, "type": elem["type"] }
                network_devices.append(network_device)
    
    return network_devices

def read_hotspots(token, hostname):
    with tempfile.NamedTemporaryFile(delete=False) as tmp_file:
        tmp_file.write(token)
        tmp_file.flush()
        bash_command = "/usr/libexec/nethserver/dedalo-hotspot-list %s %s" % (hostname, tmp_file.name)
        process = subprocess.Popen(bash_command.split(), stdout=subprocess.PIPE)
        output, error = process.communicate()

        if not output:
            return { "message": "Error retrieving hotspot list" }
        else:
            outputJson = simplejson.loads(output)

            if "message" in outputJson:
                # an error has occured
                return outputJson
            else:
                return { "hotspots": outputJson }

def get_dhcp_range(network_address, dhcp_start=None, dhcp_end=None):
    network = ipaddress.ip_network(u''+network_address)

    if dhcp_start is not None:
        # dhcp range is present in configuration
        network_ip_string = network_address.split("/")[0]
        network_int = int(ipaddress.IPv4Address(u'' + network_ip_string))
        dhcp_range_start_int = network_int + int(dhcp_start)
        dhcp_range_end_int = network_int + int(dhcp_end)

        dhcp_range_start = str(ipaddress.IPv4Address(dhcp_range_start_int))
        dhcp_range_end = str(ipaddress.IPv4Address(dhcp_range_end_int))
        return { "start": dhcp_range_start, "end": dhcp_range_end }
    else:
        # dhcp range not present in configuration, using default
        hosts = list(network.hosts())
        first, last = str(hosts[0]), str(hosts[-1])

        # first address is reserved for hotspot
        firstClient = int(ipaddress.IPv4Address(u'' + first)) + 1
        first = str(ipaddress.IPv4Address(firstClient))
        return { "start": first, "end": last }

try:
    line = fileinput.input()[0].rstrip()
    input_json = simplejson.loads(line)
    app_info = input_json["appInfo"]

    if app_info == 'hotspots':
        token = input_json["token"]
        hostname = input_json["hostname"]
        hotspots = read_hotspots(token, hostname)
        output = simplejson.dumps(hotspots)
        print (output)

        # if output json contains a message object, return exit code 1
        if 'message' in hotspots:
            sys.exit(1)
    elif app_info == 'networkDevices':
        network_devices = read_network_devices()
        output = simplejson.dumps({'networkDevices': network_devices})
        print (output)
    elif app_info == 'hostname':
        output = simplejson.dumps({'hostname': socket.gethostname()})
        print (output)
    elif app_info == 'dhcpRange':
        network_address = input_json["networkAddress"]

        if "dhcpStart" in input_json:
            dhcp_start = input_json['dhcpStart']
            dhcp_end = input_json['dhcpEnd']
            dhcp_range = get_dhcp_range(network_address, dhcp_start=dhcp_start, dhcp_end=dhcp_end)
        else:
            dhcp_range = get_dhcp_range(network_address)

        output = simplejson.dumps({'dhcpRange': dhcp_range})
        print (output)
except Exception, e:
    print simplejson.dumps({ 'error': "%s" % e })
    sys.exit(1)
