#!/bin/bash

#
# Copyright (C) 2020 Nethesis S.r.l.
# http://www.nethesis.it - nethserver@nethesis.it
#
# This script is part of NethServer.
#
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
#
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see COPYING.
#

hotspot_interface_type=$(/sbin/e-smith/db networks showjson | /usr/bin/jq -r '.[] | select(.props.role=="hotspot") | .type')

if [ -n "$hotspot_interface_type" ]
then
	hotspot_interface=$(/sbin/e-smith/db networks showjson | /usr/bin/jq -r '.[] | select(.props.role=="hotspot") | .name')

	if [ "$hotspot_interface_type" == "vlan" ]
	then
		hotspot_interface=$(echo $hotspot_interface | cut -d '.' -f 1)
	fi

	/sbin/ethtool -K $hotspot_interface gso off gro off tso off
fi
