#!/bin/bash

#
# Copyright (C) 2018 Nethesis S.r.l.
# http://www.nethesis.it - nethserver@nethesis.it
#
# This script is part of NethServer.
#
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
#
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see COPYING.
#

set -e

# Enable dedalo service
/sbin/e-smith/config setprop dedalo status disabled Id ''

# retrieve internal unit ID
dedalo_config=$(/sbin/e-smith/config getjson dedalo)
icaro_host=$(echo $dedalo_config | jq -r ".props.IcaroHost")
uuid=$(echo $dedalo_config | jq -r ".props.Uuid")
token=$(cat ~/.dedalo-token | jq -r ".token")
unit_data=$(curl -X GET --url https://$icaro_host/api/units?q=$uuid --header "Token: $token" --header "Content-Type: application/json" -s)
id=$(echo $unit_data | jq -r ".data | .[0].id")

# unregister unit
curl -X DELETE --url https://$icaro_host/api/units/$id --header "Token: $token" --header "Content-Type: application/json" -s
