#!/bin/bash

#
# Copyright (C) 2018 Nethesis S.r.l.
# http://www.nethesis.it - nethserver@nethesis.it
#
# This script is part of NethServer.
#
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
#
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see COPYING.
#

uuid=$(/sbin/e-smith/config getprop dedalo Uuid)
unit_name=$(/sbin/e-smith/config getprop dedalo UnitName)

if [ -z "$uuid" ]; then
    /sbin/e-smith/config setprop dedalo Uuid $(uuidgen)
fi

# Make sure dedalo_users_auth status is aligned to dedalo service
status=$(/sbin/e-smith/config getprop dedalo status)
/sbin/e-smith/config setprop dedalo_users_auth status "$status"

# Apply configuration
dedalo config
